# Generated by Django 5.2 on 2025-08-19 10:24

import myapp.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='Default_images/default.jpg', null=True, upload_to=myapp.accounts.models.task_file_upload_path),
        ),
    ]
