# Generated by Django 5.2 on 2025-08-07 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='uploaded_by',
        ),
    ]
