# Generated by Django 5.2 on 2025-08-07 07:11

import myapp.tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_attachment_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file_of_task',
            field=models.FileField(blank=True, null=True, upload_to=myapp.tasks.models.task_file_upload_path_title),
        ),
    ]
