# Generated by Django 5.2 on 2025-08-07 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_file_of_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='file',
            new_name='attach_file',
        ),
    ]
