# Generated by Django 5.2 on 2025-08-11 10:24

import myapp.tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attach_file',
            field=models.FileField(blank=True, null=True, upload_to=myapp.tasks.models.task_file_upload_path_name),
        ),
    ]
